packages:
  - "docs"
  - "editors/codemirror-styx"
  - "editors/monaco-styx"
  - "editors/vscode-styx"
  - "implementations/styx-js"
  - "tools/styx-webmd"
  - "crates/styx-wasm"
  - "playgrounds/monaco"
  - "playgrounds/codemirror"
