/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const render_markdown: (a: number, b: number) => any;
export const abort: () => void;
export const calloc: (a: number, b: number) => number;
export const clock: () => number;
export const dup: (a: number) => number;
export const fclose: (a: number) => number;
export const fdopen: (a: number, b: number) => number;
export const fputc: (a: number, b: number) => number;
export const fputs: (a: number, b: number) => number;
export const free: (a: number) => void;
export const fwrite: (a: number, b: number, c: number, d: number) => number;
export const iswalnum: (a: number) => number;
export const iswalpha: (a: number) => number;
export const iswdigit: (a: number) => number;
export const iswlower: (a: number) => number;
export const iswspace: (a: number) => number;
export const iswupper: (a: number) => number;
export const iswxdigit: (a: number) => number;
export const malloc: (a: number) => number;
export const memchr: (a: number, b: number, c: number) => number;
export const realloc: (a: number, b: number) => number;
export const strchr: (a: number, b: number) => number;
export const strcmp: (a: number, b: number) => number;
export const strncmp: (a: number, b: number, c: number) => number;
export const strncpy: (a: number, b: number, c: number) => number;
export const towlower: (a: number) => number;
export const towupper: (a: number) => number;
export const wasm_bindgen__closure__destroy__h2f7fb7d0886ed8c7: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc8a8310e48c5c33a: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hf5df86b8ecc6dc2c: (a: number, b: number, c: any) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
